name: MCBlender
version: 1.0-SNAPSHOT
main: com.motompro.mcblender.core.MCBlenderPlugin
authors: [ "TomMo" ]
commands:
  mcbspawn:
    aliases: [ "mcbs" ]
    permission: "command.mcblender.mcbspawn"
  mcbremove:
    aliases: [ "mcbr" ]
    permission: "command.mcblender.mcbremove"
